void XFree(void) {}
void XSync(void) {}
void XFreePixmap(void) {}
void XCreatePixmap(void) {}
void XChangeProperty(void){}
void XDeleteProperty(void){}
void XGetWindowProperty(void){}
void XTextWidth(void){}
void XCopyArea(void){}
void XFillRectangle(void){}
void XTextExtents(void){}
void XClearWindow(void){}
void XClearArea(void){}
void XDrawString(void){}
void XInternAtom(void){}
void XWindowEvent(void){}
void XDrawArc(void){}
void XDrawRectangle(void){}
void XFillArc(void){}
void XCopyPlane(void){}
void XFillPolygon(void){}
void XRaiseWindow(void){}
void _XDefaultError(void){}
void XSetErrorHandler(void){}
void XDrawLines(void){}
void XDrawLine(void){}
void XFindContext(void){}
void XFlush(void){}
void XLookupString(void){}
void XGetKeyboardMapping(void){}
void XDisplayKeycodes(void){}
void XGetAtomName(void){}
void XQueryTree(void){}
void XTranslateCoordinates(void){}
void XSetWMHints(void){}
void XSetWMNormalHints(void){}
void XAllocSizeHints(void){}
void XNextRequest(void){}
void XGetGeometry(void){}
void XWithdrawWindow(void){}
void XSetTransientForHint(void){}
void XSetWMName(void){}
void XStringListToTextProperty(void){}
void XSetIconName(void){}
void XIconifyWindow(void){}
void XSendEvent(void){}
void XInternAtoms(void){}
void XSetClassHint(void){}
void XAllocClassHint(void){}
void XDefineCursor(void){}
void XDeleteContext(void){}
void XMapWindow(void){}
void XRootWindow(void){}
void XCreateWindow(void){}
void XSaveContext(void){}
void XConfigureWindow(void){}
void XUnmapWindow(void){}
void XMoveWindow(void){}
void XResizeWindow(void){}
void XMoveResizeWindow(void){}
void XSetWindowBorderWidth(void){}
void XChangeWindowAttributes(void){}
void XSetWindowBackground(void){}
void XSetWindowBackgroundPixmap(void){}
void XPutBackEvent(void){}
void XQueryPointer(void){}
void XSetSelectionOwner(void){}
void XConvertSelection(void){}
void XSelectInput(void){}
void XrmUniqueQuark(void){}
void XOpenDisplay(void){}
void XSynchronize(void){}
void XDestroyWindow(void){}
void XSetWindowBorder(void){}
void XSetWindowBorderPixmap(void){}
void XNextEvent(void){}
void XCheckIfEvent(void){}
void XLoadQueryFont(void){}
void XFreeFont(void){}
void XGetFontProperty(void){}
void XCreateGC(void){}
void XFreeGC(void){}
void XGrabPointer(void){}
void XGrabKeyboard(void){}
void XUngrabPointer(void){}
void XUngrabKeyboard(void){}
void XLoadFont(void){}
void XCreateGlyphCursor(void){}
void XReadBitmapFile(void){}
void XParseColor(void){}
void XCreatePixmapCursor(void){}
void XCreateBitmapFromData(void){}
void XFreeCursor(void){}
void XEventsQueued(void){}
void XNoOp(void){}
void XAllocNamedColor(void){}
void XAllocColor(void){}
void XFreeColors(void){}
void XGetVisualInfo(void){}
void XCreateColormap(void){}
void XDefaultVisualOfScreen(void){}
void XDefaultDepthOfScreen(void){}
void XDefaultColormapOfScreen(void){}
void XSetForeground(void){}
void XSetLineAttributes(void){}
void XSetFillStyle(void){}
void XSetTSOrigin(void){}
void XSetStipple(void){}
void XSetFont(void){}
//void DecRefDisplay(void){}
//void IncRefDisplay(void){}
//void FindXDisplay(void){}
void XSetBackground(void){}
void XSetGraphicsExposures(void){}
void XQueryExtension(void){}
void XShmQueryVersion(void){}
void XServerVersion(void){}
void XShmDetach(void){}
void XSetCreateImage(void){}
void XShmAttach(void){}
void XCreateImage(void){}
void XServerVendor(void){}
void XShmCreatePixmap(void){}
void XShmCreateImage(void){}
void XSetClipOrigin(void){}
void XSetClipMask(void){}
void XShapeCombineMask(void){}
void XShapeQueryExtension(void){}
void XPutImage(void){}
void XDrawSegments(void){}
void XSetDashes(void){}
void XWarpPointer(void){}
void XpmReadFileToPixmap(void){}
void XpmReadFileToImage(void){}
void XCreatePixmapFromBitmapData(void){}


